name: Deploy Niun Backend Opt

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 1. Ir a la carpeta del proyecto
            cd /opt/vault_backend
            
            # 2. Configuración de seguridad de git (por si acaso)
            git config --global --add safe.directory /opt/vault_backend
            
            # 3. Descargar los últimos cambios
            git pull origin main
            
            # 4. Activar entorno y actualizar librerías
            source venv/bin/activate
            pip install -r requirements.txt
            
            # 5. Comandos de Django (Base de datos y Estáticos)
            export DJANGO_SETTINGS_MODULE=vault_backend.settings.prod
            python manage.py migrate
            python manage.py collectstatic --noinput
            
            # 6. Reiniciar el servicio de Django
            systemctl restart niun